
###############################################################################
#
# Inclusive Makefile for the BigList module.
#
# Autogenerated 2025-10-29 06:04:22.186933
#
###############################################################################
BigList_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

