
###############################################################################
#
# Inclusive Makefile for the cjson module.
#
# Autogenerated 2025-10-29 06:04:22.138496
#
###############################################################################
cjson_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

