
###############################################################################
#
# Inclusive Makefile for the cjson_util module.
#
# Autogenerated 2025-10-29 06:04:22.232997
#
###############################################################################
cjson_util_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

