
###############################################################################
#
# Inclusive Makefile for the onlplib module.
#
# Autogenerated 2025-10-29 06:04:21.952906
#
###############################################################################
onlplib_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

