
###############################################################################
#
# Inclusive Makefile for the x86_64_cel_belgite module.
#
# Autogenerated 2025-10-31 14:52:48.473210
#
###############################################################################
x86_64_cel_belgite_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_cel_belgite_BASEDIR)module/make.mk
include $(x86_64_cel_belgite_BASEDIR)module/src/make.mk
include $(x86_64_cel_belgite_BASEDIR)module/auto/make.mk

