#!/usr/bin/python3

"""mkshar

Generate a shar (with a zip file payload) for a Switch Light installer.
"""

import sys, os, shutil
import subprocess
import hashlib
import optparse

HELP = """\
%prog [OPTIONS] SHAR-OUTPUT SFX-FRAGMENT INSTALL-SCRIPT [ARG ...]
"""

parser = optparse.OptionParser(usage=HELP)
parser.add_option('--blocksize',
                  type=int, default=512,
                  help="Set block size for e.g. 'dd'")
parser.add_option('--bzip',
                  action='store_true',
                  help="Enable bzip2")
parser.add_option('--lazy',
                  action='store_true',
                  help="Enable lazy unpacking")
parser.add_option('--unzip-sfx',
                  action='store_true',
                  help="Use 'unzip' to natively handle SFX preamble")
parser.add_option('--unzip-pipe',
                  action='store_true',
                  help="Enable 'dd' to handle SFX preamble")
parser.add_option('--unzip-loop',
                  action='store_true',
                  help="Enable 'losetup' to handle SFX preamble")
parser.add_option('--unzip-pad',
                  action='store_true',
                  help="Special pad options for deficient unzip")
parser.add_option('--inplace',
                  action='store_true',
                  help="Perform fixups in-place")
parser.add_option('--fixup-perms',
                  type=str,
                  help="Post-unpack shell script to fix permissions")

opts, args = parser.parse_args()

ZIP = "/usr/bin/zip"
ZIP_OPTS = ['-v',
            '-y',
            '-n', '.zip:.loader:.swi:.jar:.gz:.bz:.bz2:.xz',]

# enable (experimental) bzip2, make sure that
# busybox unzip supports it
# Ha ha, using '-9' not only cranks up the compression,
# but *ignores* the suffix list for 'store-only'.
if opts.bzip:
    ZIP_COMPRESS_OPTS = ['-Z', 'bzip2', '-8',]
else:
    ZIP_COMPRESS_OPTS = ['-8',]

shar = args.pop(0)
sfx = args.pop(0)
install = args.pop(0)

import logging
logging.basicConfig()
logger = logging.getLogger("mkshar")
logger.setLevel(logging.DEBUG)

logger.info("initializing ZIP")
zipFile = os.path.abspath(shar + ".zip.in")
if os.path.exists(zipFile):
    logger.debug("+ /bin/rm %s", zipFile)
    os.unlink(zipFile)

def _addfile(path, *opts):
    logger.info("adding file %s with opts %s",
                path, " ".join(opts))
    cmd = [ZIP,] + ZIP_OPTS + list(opts) + ['-u', zipFile, path,]
    subprocess.check_call(cmd)

def _addfiles(paths, *opts):
    logger.info("adding %d files with opts %s",
                len(paths), " ".join(opts))
    cmd = [ZIP,] + ZIP_OPTS + list(opts) + [zipFile,] + paths
    subprocess.check_call(cmd)

def _zipopts(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in ('.loader', '.zip', '.swi',):
        return ['-0',]
    else:
        return ZIP_COMPRESS_OPTS

# block to 512 bytes
# Read as bytes from the start to avoid encoding issues
buf = open(sfx, 'rb').read()
# Convert to string for find/replace operations
buf = buf.decode('utf-8')
sz = len(buf)
logger.info("script size is %d bytes", sz)
rem = sz % opts.blocksize
pad = opts.blocksize - rem

# extra block for house keeping
if opts.unzip_pad:
    pad = pad + opts.blocksize

if pad == 1:
    buf += "\n"
elif pad > 1:
    pad -= 1
    buf = buf + ('#' * pad) + "\n"

logger.info("padded script size is %d bytes", len(buf))

if opts.unzip_pad:
    logger.info("adding SFX pad to beginning as archive item")
    fd = open("pad.bin", "w")
    fd.write(('#' * (len(buf)-1)))
    fd.write('\n')
    fd.close()
    _addfile("pad.bin", '-0', '-j')
    os.unlink("pad.bin")

_addfile(install, '-0')

if opts.fixup_perms:
    _addfile(opts.fixup_perms, '-0')

logger.info("adding other payload items")
o = ['-r',] + ZIP_COMPRESS_OPTS
_addfiles(args, *o)

def _splice(tag, val):
    global buf
    pat = tag + '='
    p = buf.find(pat)
    q = buf.find("\n", p+1)
    if p < 0:
        raise ValueError("cannot find tag %s" % repr(tag))
    llen = q - p
    line = "%s=%s #" % (tag, str(val),)
    if len(line) > llen:
        raise SystemExit("cannot insert byte count marker")
    llen -= len(line)
    line = line + ('#' * llen)
    buf = buf[:p] + line + buf[q:]

def _spliceMaybe(tag, val):
    val = "${%s-\"%s\"}" % (tag, val,)
    _splice(tag, val)

logger.info("prepping SFX")

_splice('SFX_BYTES', len(buf))
_splice('SFX_BLOCKSIZE', opts.blocksize)
_splice('SFX_INSTALL', os.path.split(install)[1])
_splice('SFX_CHECKSUM', '')
if opts.lazy:
    _splice('SFX_LAZY', '1')
else:
    _splice('SFX_LAZY', '')
if opts.unzip_sfx:
    _spliceMaybe('SFX_UNZIP', '1')
else:
    _spliceMaybe('SFX_UNZIP', '')
if opts.unzip_pipe:
    _spliceMaybe('SFX_PIPE', '1')
else:
    _spliceMaybe('SFX_PIPE', '')
if opts.unzip_loop:
    _spliceMaybe('SFX_LOOP', '1')
else:
    _spliceMaybe('SFX_LOOP', '')
if opts.unzip_pad:
    _splice('SFX_PAD', 'pad.bin')
else:
    _splice('SFX_PAD', '')
if opts.fixup_perms:
    _splice('SFX_PERMS', opts.fixup_perms)
if opts.inplace:
    _spliceMaybe('SFX_INPLACE', '1')
else:
    _spliceMaybe('SFX_INPLACE', '')

# remember the checksum offset (in bytes for binary file operations)
buf_for_find = buf.encode('utf-8') if isinstance(buf, str) else buf
ckStart = buf_for_find.find(b"SFX_CHECKSUM=")
ckEnd = buf_for_find.find(b"\n", ckStart+1)

logger.info("generating shar")

if opts.unzip_pad:

    wfd = open(shar, "wb+")
    rfd = open(zipFile, "rb")
    shutil.copyfileobj(rfd, wfd)
    rfd.close()

    logger.info("capturing first block")
    wfd.seek(0, 0)
    magic = wfd.read(opts.blocksize)

    logger.info("splicing in SFX")
    wfd.seek(0, 0)
    wfd.write(buf.encode('utf-8') if isinstance(buf, str) else buf)

    logger.info("saving first block")
    wfd.seek(len(buf)-opts.blocksize, 0)
    wfd.write(magic)

    wfd.close()

    # adjust buf to include magic
    # magic is binary data (ZIP), so we need to work with bytes
    # Keep buf as string for later operations, but note that the last block is binary
    # This is OK because we only use buf for finding text markers before this point
    # and for computing checksums (which we'll handle separately)

else:

    wfd = open(shar, "wb")
    wfd.write(buf.encode('utf-8') if isinstance(buf, str) else buf)
    rfd = open(zipFile, "rb")
    shutil.copyfileobj(rfd, wfd)
    rfd.close()
    wfd.close()

    logger.info("adjusting SFX")
    cmd = [ZIP,] + ZIP_OPTS + ['-A', shar,]
    subprocess.check_call(cmd)

# compute the actual checksum
# The verification script uses sed to delete lines matching ^SFX_CHECKSUM=
# which removes from the start of the line to the newline (inclusive)
# We need to read the actual file and compute the checksum
ckf = hashlib.md5()

# Read the entire header from the file (not from memory buffer)
rfd = open(shar, "rb")
header_data = rfd.read(len(buf.encode('utf-8') if isinstance(buf, str) else buf))
rfd.close()

# Find the SFX_CHECKSUM line in the actual file data
ckStart_file = header_data.find(b"SFX_CHECKSUM=")
ckEnd_file = header_data.find(b"\n", ckStart_file+1)

# Find the start of the line containing SFX_CHECKSUM=
line_start = header_data.rfind(b'\n', 0, ckStart_file)
if line_start == -1:  # No newline found, it's the first line
    line_start = 0
else:
    line_start += 1  # Skip the newline character itself

# Hash everything except the SFX_CHECKSUM line
ckf.update(header_data[:line_start])
ckf.update(header_data[ckEnd_file+1:])

# Hash the payload (everything after the header)
rfd = open(shar, "rb")
rfd.seek(len(header_data), 0)
while True:
    chunk = rfd.read(10*1024)
    if not chunk: break
    ckf.update(chunk)
rfd.close()

logger.info("adjusting checksum")
wfd = open(shar, "rb+")
wfd.seek(ckStart_file, 0)
checksum_line = ("SFX_CHECKSUM=%s #" % ckf.hexdigest()).encode('utf-8')
wfd.write(checksum_line)
wfd.close()

logger.info("+ /bin/chmod +x %s", shar)
os.chmod(shar, 0o755)

logger.debug("+ /bin/rm %s", zipFile)
os.unlink(zipFile)
